# 
# TransicaoInvalida, ConfigInvalida, ValidacaoAtributo.
class SmartHomeError(Exception): ...
class DispositivoJaExiste(SmartHomeError): ...
class DispositivoNaoEncontrado(SmartHomeError): ...
class ComandoInvalido(SmartHomeError): ...
class AtributoInvalido(SmartHomeError): ...
class ConfigInvalida(SmartHomeError): ...
class ErroDeValidacao(SmartHomeError):
	"""Exceção para erros de validação de comandos, atributos ou rotinas."""
	def __init__(self, mensagem, detalhes=None):
		super().__init__(mensagem)
		self.detalhes = detalhes